package com.astro.storm.data.localization

/**
 * PDF and Image Export string keys
 * Part 6 of split enums
 */
enum class StringKeyExport(override val en: String, override val ne: String) : StringKeyInterface {
    EXPORT_REPORT_TITLE("VEDIC ASTROLOGY REPORT", "वैदिक ज्योतिष रिपोर्ट"),
    EXPORT_PERSONAL_DETAILS("PERSONAL DETAILS", "व्यक्तिगत विवरण"),
    EXPORT_BIRTH_DATA("Birth Data", "जन्म विवरण"),
    EXPORT_LOCATION("Location", "स्थान"),
    EXPORT_COORDINATES("Coordinates", "निर्देशांक"),
    EXPORT_TIMEZONE("Timezone", "समय क्षेत्र"),
    
    EXPORT_ASTRO_DETAILS("ASTROLOGICAL DETAILS", "ज्योतिषीय विवरण"),
    EXPORT_PLANETARY_POSITIONS("PLANETARY POSITIONS", "ग्रह स्थिति"),
    EXPORT_HOUSE_CUSPS("HOUSE CUSPS", "भाव स्पष्ट"),
    
    EXPORT_YOGA_ANALYSIS("YOGA ANALYSIS", "योग विश्लेषण"),
    EXPORT_KEY_YOGAS("KEY AUSPICIOUS YOGAS", "मुख्य शुभ योगहरू"),
    EXPORT_CHALLENGING_YOGAS("CHALLENGING YOGAS", "चुनौतीपूर्ण योगहरू"),
    
    EXPORT_SHADBALA_ANALYSIS("SHADBALA STRENGTH", "षड्बल विश्लेषण"),
    EXPORT_ASHTAKAVARGA("ASHTAKAVARGA (SAV)", "अष्टकवर्ग (SAV)"),
    
    EXPORT_DASHA_TIMELINE("PLANETARY PERIODS (DASHA)", "ग्रह अवधि (दशा)"),
    EXPORT_CURRENT_PERIODS("Current Periods", "वर्तमान अवधिहरू"),
    EXPORT_MAHADASHAS("Mahadasha Sequence", "महादशा क्रम"),
    
    EXPORT_NAKSHATRA_DETAILS("NAKSHATRA ANALYSIS", "नक्षत्र विश्लेषण"),
    EXPORT_BIRTH_STAR("Birth Star (Janma Nakshatra)", "जन्म नक्षत्र"),
    
    EXPORT_DOSHA_ANALYSIS("DOSHA & TRANSIT ANALYSIS", "दोष र गोचर विश्लेषण"),
    EXPORT_MANGLIK_TITLE("Manglik Dosha (Kuja Dosha)", "मांगलिक दोष"),
    EXPORT_PITRA_TITLE("Pitra Dosha", "पितृ दोष"),
    EXPORT_SADE_SATI_TITLE("Sade Sati (Saturn Transit)", "साढे साती"),
    
    EXPORT_REMEDIES_TITLE("RECOMMENDED REMEDIES", "सिफारिस गरिएका उपायहरू"),
    EXPORT_GEMSTONES("Gemstone Recommendations", "रत्न सिफारिस"),
    EXPORT_MANTRAS("Mantra Recommendations", "मन्त्र सिफारिस"),
    EXPORT_CHARITY("Charity Recommendations", "दान सिफारिस"),
    
    EXPORT_GENERATED_BY("Generated by AstroStorm - Precision Vedic Astrology", "AstroStorm द्वारा उत्पन्न - सटीक वैदिक ज्योतिष"),
    EXPORT_CONFIDENTIAL("Strictly Confidential • For Personal Use Only", "अत्यन्त गोप्य • व्यक्तिगत प्रयोगका लागि मात्र"),
    
    EXPORT_PLANET("Planet", "ग्रह"),
    EXPORT_SIGN("Zodiac Sign", "राशि"),
    EXPORT_DEGREE("Degree", "अंश"),
    EXPORT_HOUSE("House", "भाव"),
    EXPORT_NAKSHATRA("Nakshatra", "नक्षत्र"),
    EXPORT_PADA("Pada", "पद"),
    EXPORT_RULER("Ruler", "स्वामी"),
    EXPORT_DEITY("Deity", "देवता"),
    
    EXPORT_VAL_NA("N/A", "उपलब्ध छैन"),
    EXPORT_VAL_UNKNOWN("Unknown", "अज्ञात"),
    EXPORT_VAL_NONE("None", "छैन"),
    
    EXPORT_LEVEL("Level", "स्तर"),
    EXPORT_STATUS("Status", "स्थिति"),
    EXPORT_CANCELLATION("Cancellation", "रद्द"),
    EXPORT_SEVERITY("Severity", "तीव्रता"),
    EXPORT_DURATION("Duration", "अवधि"),
    EXPORT_ENDS("Ends", "समाप्त"),
    EXPORT_STATUS_CURRENT("CURRENT", "वर्तमान"),
    EXPORT_STATUS_UPCOMING("UPCOMING", "आगामी"),
    EXPORT_STATUS_COMPLETED("COMPLETED", "पूरा भयो"),
    EXPORT_TO("to", "देखि"),
    EXPORT_YOGA_AUSPICIOUS("Auspicious", "शुभ"),
    EXPORT_YOGA_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    EXPORT_PRIMARY("Primary", "प्राथमिक"),
    EXPORT_ALTERNATIVES("Alternatives", "विकल्पहरू"),
    EXPORT_NO_GEMSTONES("No gemstone recommendations at this time", "यस समयमा कुनै रत्न सिफारिस छैन"),
    EXPORT_GENERAL("General", "सामान्य"),
    EXPORT_VAL_PRESENT("PRESENT", "उपस्थित"),
    EXPORT_VAL_NOT_PRESENT("NOT PRESENT", "उपस्थित छैन"),
    EXPORT_VAL_INDICATED("INDICATED", "देखिएको"),
    EXPORT_VAL_NOT_INDICATED("NOT INDICATED", "नदेखिएको"),
    EXPORT_VAL_ACTIVE("ACTIVE", "सक्रिय"),
    EXPORT_VAL_NOT_ACTIVE("NOT ACTIVE", "सक्रिय छैन"),
    EXPORT_MARS_PLACEMENT_OK("Mars is not placed in houses 1, 2, 4, 7, 8, or 12 in a way that causes Manglik Dosha.", "मंगल १, २, ४, ७, ८, वा १२ भावमा मांगलिक दोष सिर्जना गर्ने गरी बसेको छैन।"),
    EXPORT_PITRA_OK("No significant Pitra Dosha indicators found in the chart.", "कुण्डलीमा कुनै महत्त्वपूर्ण पितृ दोष सूचकहरू फेला परेनन्।"),
    EXPORT_SADE_SATI_OK("Saturn is not currently transiting near your Moon sign.", "शनि हाल तपाईंको चन्द्र राशि नजिक गोचर गरिरहेको छैन।"),
    EXPORT_PHASE("Phase", "चरण"),
    EXPORT_AREA("Area", "क्षेत्र")
}
